"""
Publishes authored content into the game: web/src/engine/gameContent.mjs, which data.mjs,
progression.mjs and survivors.mjs read their tables from. Live categories are written in the
exact shapes the engine uses; research, perks and the story ride along for systems to come.
"""

import hashlib
import json
from pathlib import Path
from typing import Dict, Any, List

from .campaign_schema import campaign_tables

GENERATED_PATH = Path("web/src/engine/gameContent.mjs")

BUILDING_FIELDS = ["name", "subtitle", "w", "h", "hp", "cost", "icon", "color"]
UPGRADE_FIELDS = ["id", "name", "description", "cost", "requires"]
ROLE_FIELDS = ["name", "building", "icon", "description"]
QUEST_FIELDS = ["id", "rank", "title", "brief", "objectives", "unlock", "reward", "log", "chapter", "giver"]
RANK_FIELDS = ["id", "name", "tier", "blurb", "milestones", "reward", "log"]
EXPEDITION_FIELDS = ["name", "description", "hours", "cost", "reward", "risk", "rescueChance", "recruit", "weapon"]
WEAPON_FIELDS = ["name", "melee", "damage", "range", "cooldown", "cost", "recipe"]


def pick(item: Dict[str, Any], fields: List[str]) -> Dict[str, Any]:
    return {k: item[k] for k in fields if k in item and item[k] is not None}


def objective(x: Dict[str, Any]) -> Dict[str, Any]:
    out = {"kind": x["kind"], "count": x["count"]}
    if x["kind"] == "build":
        out["type"] = x.get("type")
    if x["kind"] == "staff":
        out["role"] = x.get("role")
    return out


def engine_tables(content: Dict[str, List[Dict[str, Any]]]) -> Dict[str, Any]:
    buildables, jobs = content.get("buildables", []), content.get("jobs", [])
    rank_index = {r["id"]: i for i, r in enumerate(content.get("ranks", []))}

    buildings, trees = {}, {}
    for b in buildables:
        entry = pick(b, BUILDING_FIELDS)
        if b.get("fixture"):
            entry["fixture"] = True
        buildings[b["id"]] = entry
        trees[b["id"]] = [{**pick(n, UPGRADE_FIELDS), "requires": n.get("requires") or None} for n in b.get("upgrades", [])]

    roles, job_names, job_of, role_for, posts, careers = {}, {}, {}, {}, {}, {}
    for j in jobs:
        job_names[j["id"]] = j["name"]
        careers[j["id"]] = pick(j, ["description", "scaling", "workplace", "workplaceName", "workplaceBonus", "primaryStat", "secondaryStat", "careerRanks"])
        for r in j.get("roles", []):
            roles[r["id"]] = pick(r, ROLE_FIELDS)
            job_of[r["id"]] = j["id"]
            if r.get("building"):
                role_for[r["building"]] = r["id"]
                posts[r["building"]] = {"role": r["id"], "slots": r.get("slots", 0),
                                        "bonus": [{"upgrade": x["upgrade"], "slots": x["slots"]} for x in r.get("slotBonus", []) or []]}

    quests = []
    for q in content.get("quests", []):
        entry = pick(q, QUEST_FIELDS)
        entry["rank"] = rank_index.get(q.get("rank"), 0)
        entry["objectives"] = [objective(x) for x in q.get("objectives", [])]
        entry.setdefault("unlock", [])
        entry.setdefault("log", "")
        quests.append(entry)

    ranks = []
    for r in content.get("ranks", []):
        entry = pick(r, RANK_FIELDS)
        entry["milestones"] = [objective(x) for x in r.get("milestones", [])]
        ranks.append(entry)

    return {
        "BUILDINGS": buildings,
        "BUILDING_TREES": trees,
        "ROLES": roles,
        "JOBS": job_names,
        "JOB_OF": job_of,
        "ROLE_FOR": role_for,
        "POSTS": posts,
        "CAREERS": careers,
        "QUESTS": quests,
        "RANKS": ranks,
        "EXPEDITIONS": {e["id"]: pick(e, EXPEDITION_FIELDS) for e in content.get("expeditions", [])},
        "WEAPONS": {w["id"]: pick(w, WEAPON_FIELDS) for w in content.get("weapons", [])},
        "RESEARCH": content.get("research", []),
        "JOB_PERKS": content.get("job_perks", []),
        "SURVIVOR_PERKS": content.get("survivor_perks", []),
        "CHAPTERS": content.get("chapters", []),
        "CHARACTERS": content.get("characters", []),
        "MESSAGES": content.get("messages", []),
        "CAMPAIGN": campaign_tables(content),
    }


def to_module(content: Dict[str, List[Dict[str, Any]]]) -> str:
    tables = engine_tables(content)
    body = "".join(f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)};\n" for name, value in tables.items())
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]
    return (
        "// Generated by the content studio (python3 server.py, then open /dashboard). Do not edit by hand:\n"
        "// change the content there and publish. The authored source is backend/data/*.json.\n"
        f"export const CONTENT_HASH = '{digest}';\n" + body
    )


def publish(content: Dict[str, List[Dict[str, Any]]], root_dir: Path) -> Dict[str, Any]:
    path = root_dir / GENERATED_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    text = to_module(content)
    changed = not path.exists() or path.read_text(encoding="utf-8") != text
    if changed:
        tmp = path.with_suffix(".mjs.tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    return {"status": "published", "path": str(GENERATED_PATH), "changed": changed, "bytes": len(text.encode("utf-8"))}


def is_published(content: Dict[str, List[Dict[str, Any]]], root_dir: Path) -> bool:
    path = root_dir / GENERATED_PATH
    return path.exists() and path.read_text(encoding="utf-8") == to_module(content)
